services:
  oracle.fiap.com.br:
    container_name: orcl_gestao
    image: container-registry.oracle.com/database/free:latest
    ports:
      - "1521:1521"   # Porta padrão do Oracle Database
      - "5500:5500"   # Porta do Oracle Enterprise Manager (opcional)
    environment:
      - ORACLE_PWD=manager   # Senha para o usuário SYS, SYSTEM
      - ORACLE_CHARACTERSET=AL32UTF8  # Define o charset para AL32UTF8

  api:
    build: .
    ports:
      -"8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
      - DATABASE_USER=RM99300
      - DATABASE_PWD=030203
    depends_on:
      - oracle.fiap.com.br